# Generated by Django 3.0.2 on 2020-01-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('days', models.CharField(max_length=50)),
                ('offer', models.BooleanField(default=False)),
                ('valid_till', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
