# Generated by Django 3.0.2 on 2020-01-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200109_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
