# Generated by Django 3.0.2 on 2020-01-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_destinations_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
