# Generated by Django 3.0.2 on 2020-01-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200112_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
    ]
