# Generated by Django 3.0.2 on 2020-01-12 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200113_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
    ]
